version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      dev-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "benchmark"
          - "brakeman"
          - "capybara"
          - "capybara-screenshot"
          - "minitest"
          - "mocha"
          - "rack-mini-profiler"
          - "rubocop*"
          - "selenium-webdriver"
          - "standard"
          - "testcontainers-postgres"
          - "vcr"
          - "web-console"
          - "webmock"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
