version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "rubocop*"
          - "capybara"
          - "minitest"
          - "standard"
          - "web-console"
          - "rack-mini-profiler"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
