# fly.toml app configuration file generated for rating on 2023-05-28T17:18:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rating"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "waw"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
