default: &default
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres") %>
  pool: 5
  variables:
    statement_timeout: <%= ENV.fetch("DATABASE_STATEMENT_TIMEOUT", 5000)%>

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

development:
  <<: *default
