default: &default
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:@localhost:5432") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5)%>
  variables:
    statement_timeout: 120000

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

development:
  <<: *default
