default: &default
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres") %>
  pool: 5
  variables:
    statement_timeout: <%= ENV.fetch("DATABASE_STATEMENT_TIMEOUT", 5000)%>
    idle_in_transaction_session_timeout: <%= ENV.fetch("DATABASE_IDLE_IN_TRANSACTION_SESSION_TIMEOUT", 300_000)%>
    lock_timeout: <%= ENV.fetch("DATABASE_LOCK_TIMEOUT", 5000)%>

replica_default: &replica_default
  adapter: postgresql
  url: <%= ENV.fetch('REPLICA_DATABASE_URL', ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres")) %>
  pool: 5
  replica: true
  variables:
    statement_timeout: <%= ENV.fetch("DATABASE_STATEMENT_TIMEOUT", 5000)%>
    idle_in_transaction_session_timeout: <%= ENV.fetch("DATABASE_IDLE_IN_TRANSACTION_SESSION_TIMEOUT", 300_000)%>
    lock_timeout: <%= ENV.fetch("DATABASE_LOCK_TIMEOUT", 5000)%>

production:
  primary:
    <<: *default
    connect_timeout: 5
    checkout_timeout: 5
  replica:
    <<: *replica_default
    connect_timeout: 5
    checkout_timeout: 5

staging:
  primary:
    <<: *default
  replica:
    <<: *replica_default

test:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgres://postgres:postgres@localhost:5432/test_db' %>
  replica:
    <<: *replica_default
    url: <%= ENV['REPLICA_DATABASE_URL'] || ENV['DATABASE_URL'] || 'postgres://postgres:postgres@localhost:5432/test_db' %>

development:
  primary:
    <<: *default
  replica:
    <<: *replica_default
