default: &default
  adapter: postgresql
  pool: 5
  variables:
    statement_timeout: <%= ENV.fetch("DATABASE_STATEMENT_TIMEOUT", 5000)%>
    idle_in_transaction_session_timeout: <%= ENV.fetch("DATABASE_IDLE_IN_TRANSACTION_SESSION_TIMEOUT", 300_000)%>
    lock_timeout: <%= ENV.fetch("DATABASE_LOCK_TIMEOUT", 5000)%>

production:
  primary:
    <<: *default
    url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres") %>
    connect_timeout: 5
    checkout_timeout: 5
  replica:
    <<: *default
    url: <%= ENV.fetch('REPLICA_DATABASE_URL', ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres")) %>
    connect_timeout: 5
    checkout_timeout: 5
    replica: true

staging:
  primary:
    <<: *default
    url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres") %>
  replica:
    <<: *default
    url: <%= ENV.fetch('REPLICA_DATABASE_URL', ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres")) %>
    replica: true

test:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgres://postgres:postgres@localhost:5432/test_db' %>
  replica:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgres://postgres:postgres@localhost:5432/test_db' %>
    replica: true

development:
  primary:
    <<: *default
    url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres") %>
  replica:
    <<: *default
    url: <%= ENV.fetch('REPLICA_DATABASE_URL', ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres")) %>
    replica: true
