default: &default
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL', "postgres://postgres:password@localhost:5432/postgres") %>
  pool: 5
  variables:
    statement_timeout: <%= ENV.fetch("DATABASE_STATEMENT_TIMEOUT", 5000)%>
    idle_in_transaction_session_timeout: <%= ENV.fetch("DATABASE_IDLE_IN_TRANSACTION_SESSION_TIMEOUT", 300_000)%>
    lock_timeout: <%= ENV.fetch("DATABASE_LOCK_TIMEOUT", 5000)%>

production:
  <<: *default
  connect_timeout: 5
  checkout_timeout: 5

staging:
  <<: *default

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgres://postgres:postgres@localhost:5432/test_db' %>

development:
  <<: *default
