default: &default
  adapter: postgresql
  database: <%= ENV.fetch('postgres_database', 'postgres') %>
  username: <%= ENV.fetch('postgres_user', 'rating_ui') %>
  password: <%= ENV.fetch('postgres_password', 'rating_ui') %>
  host: <%= ENV.fetch('postgres_host', 'localhost') %>
  port: <%= ENV.fetch('postgres_port', 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5)%>
  variables:
    statement_timeout: 120000

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

development:
  <<: *default
  database: postgres
  username: postgres
  password:
