production:
  # Every two hours we load data for the most recent tournaments
  recent_tournament_results:
    class: RecentTournamentResultsJob
    args: [ 28 ]
    schedule: 35 */2 * * *

  # Many tournaments open their results at 20:59 UTC
  just_opened_tournament_results:
    class: RecentTournamentResultsJob
    args: [ 3 ]
    schedule: 0 21 * * *

  # Once a day we update results and rosters for all tournaments in the past year
  last_year_tournament_results:
    class: RecentTournamentResultsJob
    args: [ 365 ]
    schedule: 15 2 * * *

  # Once a week we update results and rosters for all rating tournaments since September 2021
  all_rating_tournament_results:
    class: AllRatingTournamentResultsJob
    schedule: every Wednesday at 4:15

  # Once a day we refresh metadata for recently updated tournaments
  recent_tournament_metadata:
    class: TournamentsMetadataJob
    args: [ "recently_updated" ]
    schedule: every day at 2:00

  # Once a week we update metadata for all tournaments
  all_rating_tournaments_metadata:
    class: TournamentsMetadataJob
    args: [ "all" ]
    schedule: every Wednesday at 2:15

  # Names and towns for teams
  teams:
    class: TeamsJob
    schedule: 30 16 * * *

  # Names for players
  players:
    class: PlayersJob
    schedule: every day at 10:30

  # Names of towns
  towns:
    class: TownsJob
    schedule: every day at 12:00

  clear_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches"
    schedule: every day at 16:00

  backup:
    class: BackupJob
    schedule: every day at 23:30
